//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemieApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemieApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Projekt aplikace Chemie.
        ///Informace o prvcích pochází z webu Wikipedia.
        ///
        ///Změny:
        ///------
        ///1) Vylepšený design aplikace
        ///2) Nové okno &quot;O aplikaci&quot;
        ///3) Možnost zavírat okna &quot;O aplikaci&quot; a &quot;Info o prvku&quot; pomocí klávesy ESC.
        ///4) Možnost přesouvání hlavního okna aplikace po obrazovce
        ///5) Lepší vykreslování
        ///.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;infooprvku&gt;
        ///	&lt;!--Vodík--&gt;
        ///	&lt;Vodík Sekce=&quot;Název&quot; Info=&quot;Vodík&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Chemická značka&quot; Info=&quot;H&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Protonové číslo&quot; Info=&quot;1&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Latinsky&quot; Info=&quot;Hydrogenium&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Skupina&quot; Info=&quot;1. skupina&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Perioda&quot; Info=&quot;1. perioda&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Vlastnosti&quot; Info=&quot;Bezbarvý plyn&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Relativní atomová hmotnost&quot; Info=&quot;1,007 94&quot; /&gt;
        ///	&lt;!--Lithium--&gt;
        ///	&lt;Lithium Sekce=&quot;Název&quot; Info=&quot;Lithium&quot; /&gt;
        ///	&lt;Lithium Sekce=&quot;Chemická značka&quot; Info= [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string prvky {
            get {
                return ResourceManager.GetString("prvky", resourceCulture);
            }
        }
    }
}
